### ISSUE TITLE
Pktgen (versions 3.0.06, 3.0.07, 3.0.08) building fails against dpdk-16.04

### ISSUE THREAD

**Issue by hristotrifonov** [pktgen/Pktgen-DPDK#75]
Hi,

I'm trying to build the above mentioned 3 versions against dpdk-16.04 and failing with the following output:

[dpdk@dpdk pktgen-3.0.08]$ make
== lib
== common
  CC wr_copyright_info.o
  CC wr_port_config.o
  CC wr_core_info.o
  CC cmdline_parse_args.o
  CC wr_lscpu.o
  CC wr_utils.o
  CC wr_coremap.o
  CC wr_pcap.o
  CC wr_cksum.o
  CC wr_l2p.o
  CC wr_scrn.o
  AR libcommon.a
  SYMLINK-FILE include/wr_cksum.h
  SYMLINK-FILE include/wr_copyright_info.h
  SYMLINK-FILE include/wr_core_info.h
  SYMLINK-FILE include/wr_coremap.h
  SYMLINK-FILE include/cmdline_parse_args.h
  SYMLINK-FILE include/wr_cycles.h
  SYMLINK-FILE include/wr_inet.h
  SYMLINK-FILE include/wr_l2p.h
  SYMLINK-FILE include/wr_lscpu.h
  SYMLINK-FILE include/wr_mbuf.h
  SYMLINK-FILE include/wr_pcap.h
  SYMLINK-FILE include/wr_port_config.h
  SYMLINK-FILE include/wr_scrn.h
  SYMLINK-FILE include/wr_utils.h
  INSTALL-LIB libcommon.a
== lua
== src
  CC lapi.o
  CC lauxlib.o
  CC lbaselib.o
  CC lbitlib.o
  CC lcode.o
  CC lcorolib.o
  CC lctype.o
  CC ldblib.o
  CC ldebug.o
  CC ldo.o
  CC ldump.o
  CC lfunc.o
  CC lgc.o
  CC linit.o
  CC liolib.o
  CC llex.o
  CC lmathlib.o
  CC lmem.o
  CC loadlib.o
  CC lobject.o
  CC lopcodes.o
  CC loslib.o
  CC lparser.o
  CC lstate.o
  CC lutf8lib.o
  CC lstring.o
  CC lstrlib.o
  CC ltable.o
  CC ltablib.o
  CC ltm.o
  CC lua_shell.o
  CC lundump.o
  CC lvm.o
  CC lzio.o
  CC lua-socket.o
  AR liblua.a
  INSTALL-LIB liblua.a
== app
  CC cmd-functions.o
  CC lpktgenlib.o
  CC pktgen-cmds.o
  CC pktgen.o
/home/dpdk/pktgen-3.0.08/app/pktgen.c: In function ‘pktgen_setup_packets’:
/home/dpdk/pktgen-3.0.08/app/pktgen.c:1139:27: warning: passing argument 2 of ‘rte_mempool_obj_iter’ makes integer from pointer without a cast [-Wint-conversion]
  rte_mempool_obj_iter(mp, pktgen_setup_cb, &pkt_data);
                           ^
In file included from /home/dpdk/dpdk//x86_64-native-linuxapp-gcc/include/rte_mbuf.h:58:0,
                 from /home/dpdk/dpdk//x86_64-native-linuxapp-gcc/include/rte_ether.h:52,
                 from /home/dpdk/pktgen-3.0.08/app/pktgen.h:121,
                 from /home/dpdk/pktgen-3.0.08/app/pktgen.c:71:
/home/dpdk/dpdk//x86_64-native-linuxapp-gcc/include/rte_mempool.h:431:10: note: expected ‘uint32_t {aka unsigned int}’ but argument is of type ‘void (*)(struct rte_mempool *, void *, void *, unsigned int)’
 uint32_t rte_mempool_obj_iter(void *vaddr,
          ^
/home/dpdk/pktgen-3.0.08/app/pktgen.c:1139:44: warning: passing argument 3 of ‘rte_mempool_obj_iter’ makes integer from pointer without a cast [-Wint-conversion]
  rte_mempool_obj_iter(mp, pktgen_setup_cb, &pkt_data);
                                            ^
In file included from /home/dpdk/dpdk//x86_64-native-linuxapp-gcc/include/rte_mbuf.h:58:0,
                 from /home/dpdk/dpdk//x86_64-native-linuxapp-gcc/include/rte_ether.h:52,
                 from /home/dpdk/pktgen-3.0.08/app/pktgen.h:121,
                 from /home/dpdk/pktgen-3.0.08/app/pktgen.c:71:
/home/dpdk/dpdk//x86_64-native-linuxapp-gcc/include/rte_mempool.h:431:10: note: expected ‘size_t {aka long unsigned int}’ but argument is of type ‘pkt_data_t * {aka struct <anonymous> *}’
 uint32_t rte_mempool_obj_iter(void *vaddr,
          ^
/home/dpdk/pktgen-3.0.08/app/pktgen.c:1139:2: error: too few arguments to function ‘rte_mempool_obj_iter’
  rte_mempool_obj_iter(mp, pktgen_setup_cb, &pkt_data);
  ^
In file included from /home/dpdk/dpdk//x86_64-native-linuxapp-gcc/include/rte_mbuf.h:58:0,
                 from /home/dpdk/dpdk//x86_64-native-linuxapp-gcc/include/rte_ether.h:52,
                 from /home/dpdk/pktgen-3.0.08/app/pktgen.h:121,
                 from /home/dpdk/pktgen-3.0.08/app/pktgen.c:71:
/home/dpdk/dpdk//x86_64-native-linuxapp-gcc/include/rte_mempool.h:431:10: note: declared here
 uint32_t rte_mempool_obj_iter(void *vaddr,
          ^
/home/dpdk/dpdk//mk/internal/rte.compile-pre.mk:126: recipe for target 'pktgen.o' failed
make[2]: *** [pktgen.o] Error 1
/home/dpdk/dpdk//mk/rte.extapp.mk:42: recipe for target 'all' failed
make[1]: *** [all] Error 2
/home/dpdk/dpdk//mk/rte.extsubdir.mk:46: recipe for target 'app' failed
make: *** [app] Error 2

The Error output is the same for the three versions mentioned.
Can you please provide a workaround or a patch for this.
Thanks.

Best Regards,

Hristo

**Comment by pktgen** [comment]
In the least version of Pktgen it is using the new rte_mempool_obj_iter function call and is not compatible to 16.04. I thought I had ifdef’d all of the locations, but I guess not. Please use 16.07-rc5 of DPDK with the later versions of Pktgen.

**Comment by hristotrifonov** [comment]
Thanks for your suggestion. It builds fine with 16.07

Best regards,

Hristo
