### ISSUE TITLE
Having problem to build pktgen

### ISSUE THREAD

**Issue by nick8880** [pktgen/Pktgen-DPDK#236]
i have tried latest version of dpdk and pktge-dpdk, to build the pktgen but encounter errors such as "error: implicit declaration of function ‘rte_eth_bond_slaves_get’; did you mean ‘rte_eth_bond_members_get’? [-Werror=implicit-function-declaration]
 1948 |     num_workers = rte_eth_bond_slaves_get(info->pid, workers, RTE_MAX_ETHPORTS);" any idea where i have done wrong?

logs-
ktgen@pktgen-None:/pktgen-dpdk-pktgen-23.06.1$ sudo make
>>> Use 'make help' for more commands

./tools/pktgen-build.sh build
>>  SDK Path          : 
>>  Install Path      : /pktgen-dpdk-pktgen-23.06.1
>>  Build Directory   : /pktgen-dpdk-pktgen-23.06.1/Builddir
>>  Target Directory  : usr/local
>>  Build Path        : /pktgen-dpdk-pktgen-23.06.1/Builddir
>>  Target Path       : /pktgen-dpdk-pktgen-23.06.1/usr/local

 Build and install values:
   lua_enabled       : -Denable_lua=false
   gui_enabled       : -Denable_gui=false

>>> Ninja build in '/pktgen-dpdk-pktgen-23.06.1/Builddir' buildtype=release
meson setup -Dbuildtype=release -Denable_lua=false -Denable_gui=false /pktgen-dpdk-pktgen-23.06.1/Builddir
The Meson build system
Version: 1.2.1
Source dir: /pktgen-dpdk-pktgen-23.06.1
Build dir: /pktgen-dpdk-pktgen-23.06.1/Builddir
Build type: native build
Program cat found: YES (/usr/bin/cat)
Project name: pktgen
Project version: 23.06.1
C compiler for the host machine: cc (gcc 13.2.0 "cc (Ubuntu 13.2.0-4ubuntu3) 13.2.0")
C linker for the host machine: cc ld.bfd 2.41
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -mavx: YES 
Compiler for C supports arguments -mavx2: YES 
Compiler for C supports arguments -Wno-pedantic: YES 
Compiler for C supports arguments -Wno-format-truncation: YES 
Found pkg-config: /usr/bin/pkg-config (1.8.1)
Run-time dependency libdpdk found: YES 23.11.0-rc4
WARNING: find_library('librte_net_bond') starting in "lib" only works by accident and is not portable
Library librte_net_bond found: YES
Program python3 found: YES (/usr/bin/python3)
Library rte_net_i40e found: YES
Library rte_net_ixgbe found: YES
Library rte_net_ice found: YES
Library rte_bus_vdev found: YES
Run-time dependency threads found: YES
Library numa found: YES
Library pcap found: YES
Library dl found: YES
Library m found: YES
Program doxygen found: YES (/usr/bin/doxygen)
Program generate_doxygen.sh found: YES (/pktgen-dpdk-pktgen-23.06.1/doc/api/generate_doxygen.sh)
Program generate_examples.sh found: YES (/pktgen-dpdk-pktgen-23.06.1/doc/api/generate_examples.sh)
Program doxy-html-custom.sh found: YES (/pktgen-dpdk-pktgen-23.06.1/doc/api/doxy-html-custom.sh)
Configuring doxy-api.conf using configuration
Program sphinx-build found: NO
Build targets in project: 11
NOTICE: Future-deprecated features used:
 * 0.56.0: {'meson.build_root', 'meson.source_root'}

pktgen 23.06.1

  User defined options
    buildtype : release
    enable_gui: false
    enable_lua: false

Found ninja-1.11.1 at /usr/bin/ninja
ninja: Entering directory `/pktgen-dpdk-pktgen-23.06.1/Builddir'
[43/69] Compiling C object app/pktgen.p/pktgen-cmds.c.o
FAILED: app/pktgen.p/pktgen-cmds.c.o 
cc -Iapp/pktgen.p -Iapp -I../app -Ilib/common -I../lib/common -Ilib/utils -I../lib/utils -Ilib/vec -I../lib/vec -Ilib/plugin -I../lib/plugin -Ilib/cli -I../lib/cli -Ilib/lua -I../lib/lua -I/usr/local/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -O3 -march=native -mavx -mavx2 -DALLOW_EXPERIMENTAL_API -D_GNU_SOURCE -Wno-pedantic -Wno-format-truncation -pthread -include rte_config.h -march=native -mrtm '-D__PROJECT_VERSION="23.06.1"' -MD -MQ app/pktgen.p/pktgen-cmds.c.o -MF app/pktgen.p/pktgen-cmds.c.o.d -o app/pktgen.p/pktgen-cmds.c.o -c ../app/pktgen-cmds.c
../app/pktgen-cmds.c: In function ‘enable_bonding’:
../app/pktgen-cmds.c:1948:19: error: implicit declaration of function ‘rte_eth_bond_slaves_get’; did you mean ‘rte_eth_bond_members_get’? [-Werror=implicit-function-declaration]
 1948 |     num_workers = rte_eth_bond_slaves_get(info->pid, workers, RTE_MAX_ETHPORTS);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~
      |                   rte_eth_bond_members_get
../app/pktgen-cmds.c:1955:9: error: implicit declaration of function ‘rte_eth_bond_active_slaves_get’; did you mean ‘rte_eth_bond_active_members_get’? [-Werror=implicit-function-declaration]
 1955 |         rte_eth_bond_active_slaves_get(info->pid, active_workers, RTE_MAX_ETHPORTS);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         rte_eth_bond_active_members_get
../app/pktgen-cmds.c: In function ‘show_bonding_mode’:
../app/pktgen-cmds.c:2087:47: error: storage size of ‘conf’ isn’t known
 2087 |         struct rte_eth_bond_8023ad_slave_info conf;
      |                                               ^~~~
../app/pktgen-cmds.c:2090:9: error: implicit declaration of function ‘rte_eth_bond_8023ad_slave_info’; did you mean ‘rte_eth_bond_8023ad_member_info’? [-Werror=implicit-function-declaration]
 2090 |         rte_eth_bond_8023ad_slave_info(info->pid, workers[i], &conf);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         rte_eth_bond_8023ad_member_info
../app/pktgen-cmds.c:2087:47: error: unused variable ‘conf’ [-Werror=unused-variable]
 2087 |         struct rte_eth_bond_8023ad_slave_info conf;
      |                                               ^~~~
cc1: all warnings being treated as errors
[48/69] Compiling C object app/pktgen.p/cli-functions.c.o
ninja: build stopped: subcommand failed.
make: *** [Makefile:15: build] Error 1

Many thanks if someone can help one this.

**Comment by KeithWiles** [comment]
I did not see which version of DPDK you are using, but I assume v23.07. DPDK changed the names of these functions to use member(s) instead of slave(s). 

Please update Pktgen to 23.10.2 and DPDK 23.11.0-rc4 or you can modify the Pktgen code  and rename the functions to the correct names using member or members for that version of DPDK.

**Comment by lyquid617** [comment]
Same problem. I followed the INSTALL.md to download pktgen from http://dpdk.org/git/apps/pktgen-dpdk, where the newest release there is only 23.06.1.At last I downloaded pktgen from github and solved this problem.

**Comment by edmundselliot** [comment]
> Same problem. I followed the INSTALL.md to download pktgen from http://dpdk.org/git/apps/pktgen-dpdk, where the newest release there is only 23.06.1.At last I downloaded pktgen from github and solved this problem.

+1, pulling with `git clone https://github.com/pktgen/Pktgen-DPDK` solved this for me as well.

**Comment by nick8880** [comment]
Thanks everyone's comment and replying. i fixed the problem by followed the Kieth's suggestion to update the Pktgen to latest version which is rc version.
