### ISSUE TITLE
dev branch: compile error with lua or gui enabled

### ISSUE THREAD

**Issue by a-andre** [pktgen/Pktgen-DPDK#105]
Lua enabled: 
```
../pktgen-dpdk/app/lpktgenlib.c: In function 'port_info':
../pktgen-dpdk/app/lpktgenlib.c:3117:38: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
 3117 |     setf_integer(L, "broadcast", info->sizes.broadcast);
      |                                      ^~
../pktgen-dpdk/app/lpktgenlib.c:3118:38: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
 3118 |     setf_integer(L, "multicast", info->sizes.multicast);
      |                                      ^~
../pktgen-dpdk/app/lpktgenlib.c:3119:32: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
 3119 |     setf_integer(L, "_64", info->sizes._64);
      |                                ^~
../pktgen-dpdk/app/lpktgenlib.c:3120:36: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
 3120 |     setf_integer(L, "_65_127", info->sizes._65_127);
      |                                    ^~
../pktgen-dpdk/app/lpktgenlib.c:3121:37: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
 3121 |     setf_integer(L, "_128_255", info->sizes._128_255);
      |                                     ^~
../pktgen-dpdk/app/lpktgenlib.c:3122:37: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
 3122 |     setf_integer(L, "_256_511", info->sizes._256_511);
      |                                     ^~
../pktgen-dpdk/app/lpktgenlib.c:3123:38: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
 3123 |     setf_integer(L, "_512_1023", info->sizes._512_1023);
      |                                      ^~
../pktgen-dpdk/app/lpktgenlib.c:3124:39: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
 3124 |     setf_integer(L, "_1024_1518", info->sizes._1024_1518);
      |                                       ^~
../pktgen-dpdk/app/lpktgenlib.c:3125:34: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
 3125 |     setf_integer(L, "jumbo", info->sizes.jumbo);
      |                                  ^~
../pktgen-dpdk/app/lpktgenlib.c:3126:34: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
 3126 |     setf_integer(L, "runts", info->sizes.runt);
      |                                  ^~
../pktgen-dpdk/app/lpktgenlib.c:3128:39: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'stats'; did you mean 'qstats'?
 3128 |     setf_integer(L, "arp_pkts", info->stats.arp_pkts);
      |                                       ^~~~~
      |                                       qstats
../pktgen-dpdk/app/lpktgenlib.c:3129:40: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'stats'; did you mean 'qstats'?
 3129 |     setf_integer(L, "echo_pkts", info->stats.echo_pkts);
      |                                        ^~~~~
      |                                        qstats
../pktgen-dpdk/app/lpktgenlib.c:3134:40: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'stats'; did you mean 'qstats'?
 3134 |     setf_integer(L, "tx_failed", info->stats.tx_failed);
      |                                        ^~~~~
      |                                        qstats
../pktgen-dpdk/app/lpktgenlib.c:3135:38: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'stats'; did you mean 'qstats'?
 3135 |     setf_integer(L, "imissed", info->stats.imissed);
      |                                      ^~~~~
      |                                      qstats
../pktgen-dpdk/app/lpktgenlib.c:3137:38: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'stats'; did you mean 'qstats'?
 3137 |     setf_integer(L, "ibadcrc", info->stats.rx_nombuf);
      |                                      ^~~~~
      |                                      qstats
```
GUI enabled:
```
../pktgen-dpdk/app/pktgen-gui.c: In function 'update_port_statistics':
../pktgen-dpdk/app/pktgen-gui.c:295:35: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
  295 |         stats_store_next(pid, info->sizes.broadcast);
      |                                   ^~
../pktgen-dpdk/app/pktgen-gui.c:23:81: note: in definition of macro 'stats_store'
   23 |         gtk_tree_store_set(treestore_stats[(p)], &toplevel, COL_CHASSIS_PORTS, (v), -1); \
      |                                                                                 ^
../pktgen-dpdk/app/pktgen-gui.c:295:9: note: in expansion of macro 'stats_store_next'
  295 |         stats_store_next(pid, info->sizes.broadcast);
      |         ^~~~~~~~~~~~~~~~
../pktgen-dpdk/app/pktgen-gui.c:296:35: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
  296 |         stats_store_next(pid, info->sizes.multicast);
      |                                   ^~
../pktgen-dpdk/app/pktgen-gui.c:23:81: note: in definition of macro 'stats_store'
   23 |         gtk_tree_store_set(treestore_stats[(p)], &toplevel, COL_CHASSIS_PORTS, (v), -1); \
      |                                                                                 ^
../pktgen-dpdk/app/pktgen-gui.c:296:9: note: in expansion of macro 'stats_store_next'
  296 |         stats_store_next(pid, info->sizes.multicast);
      |         ^~~~~~~~~~~~~~~~
../pktgen-dpdk/app/pktgen-gui.c:297:35: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
  297 |         stats_store_next(pid, info->sizes._64);
      |                                   ^~
../pktgen-dpdk/app/pktgen-gui.c:23:81: note: in definition of macro 'stats_store'
   23 |         gtk_tree_store_set(treestore_stats[(p)], &toplevel, COL_CHASSIS_PORTS, (v), -1); \
      |                                                                                 ^
../pktgen-dpdk/app/pktgen-gui.c:297:9: note: in expansion of macro 'stats_store_next'
  297 |         stats_store_next(pid, info->sizes._64);
      |         ^~~~~~~~~~~~~~~~
../pktgen-dpdk/app/pktgen-gui.c:298:35: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
  298 |         stats_store_next(pid, info->sizes._65_127);
      |                                   ^~
../pktgen-dpdk/app/pktgen-gui.c:23:81: note: in definition of macro 'stats_store'
   23 |         gtk_tree_store_set(treestore_stats[(p)], &toplevel, COL_CHASSIS_PORTS, (v), -1); \
      |                                                                                 ^
../pktgen-dpdk/app/pktgen-gui.c:298:9: note: in expansion of macro 'stats_store_next'
  298 |         stats_store_next(pid, info->sizes._65_127);
      |         ^~~~~~~~~~~~~~~~
../pktgen-dpdk/app/pktgen-gui.c:299:35: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
  299 |         stats_store_next(pid, info->sizes._128_255);
      |                                   ^~
../pktgen-dpdk/app/pktgen-gui.c:23:81: note: in definition of macro 'stats_store'
   23 |         gtk_tree_store_set(treestore_stats[(p)], &toplevel, COL_CHASSIS_PORTS, (v), -1); \
      |                                                                                 ^
../pktgen-dpdk/app/pktgen-gui.c:299:9: note: in expansion of macro 'stats_store_next'
  299 |         stats_store_next(pid, info->sizes._128_255);
      |         ^~~~~~~~~~~~~~~~
../pktgen-dpdk/app/pktgen-gui.c:300:35: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
  300 |         stats_store_next(pid, info->sizes._256_511);
      |                                   ^~
../pktgen-dpdk/app/pktgen-gui.c:23:81: note: in definition of macro 'stats_store'
   23 |         gtk_tree_store_set(treestore_stats[(p)], &toplevel, COL_CHASSIS_PORTS, (v), -1); \
      |                                                                                 ^
../pktgen-dpdk/app/pktgen-gui.c:300:9: note: in expansion of macro 'stats_store_next'
  300 |         stats_store_next(pid, info->sizes._256_511);
      |         ^~~~~~~~~~~~~~~~
../pktgen-dpdk/app/pktgen-gui.c:301:35: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
  301 |         stats_store_next(pid, info->sizes._512_1023);
      |                                   ^~
../pktgen-dpdk/app/pktgen-gui.c:23:81: note: in definition of macro 'stats_store'
   23 |         gtk_tree_store_set(treestore_stats[(p)], &toplevel, COL_CHASSIS_PORTS, (v), -1); \
      |                                                                                 ^
../pktgen-dpdk/app/pktgen-gui.c:301:9: note: in expansion of macro 'stats_store_next'
  301 |         stats_store_next(pid, info->sizes._512_1023);
      |         ^~~~~~~~~~~~~~~~
../pktgen-dpdk/app/pktgen-gui.c:302:35: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
  302 |         stats_store_next(pid, info->sizes._1024_1518);
      |                                   ^~
../pktgen-dpdk/app/pktgen-gui.c:23:81: note: in definition of macro 'stats_store'
   23 |         gtk_tree_store_set(treestore_stats[(p)], &toplevel, COL_CHASSIS_PORTS, (v), -1); \
      |                                                                                 ^
../pktgen-dpdk/app/pktgen-gui.c:302:9: note: in expansion of macro 'stats_store_next'
  302 |         stats_store_next(pid, info->sizes._1024_1518);
      |         ^~~~~~~~~~~~~~~~
../pktgen-dpdk/app/pktgen-gui.c:305:35: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
  305 |         stats_store_next(pid, info->sizes.runt);
      |                                   ^~
../pktgen-dpdk/app/pktgen-gui.c:23:81: note: in definition of macro 'stats_store'
   23 |         gtk_tree_store_set(treestore_stats[(p)], &toplevel, COL_CHASSIS_PORTS, (v), -1); \
      |                                                                                 ^
../pktgen-dpdk/app/pktgen-gui.c:305:9: note: in expansion of macro 'stats_store_next'
  305 |         stats_store_next(pid, info->sizes.runt);
      |         ^~~~~~~~~~~~~~~~
../pktgen-dpdk/app/pktgen-gui.c:306:35: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'sizes'
  306 |         stats_store_next(pid, info->sizes.jumbo);
      |                                   ^~
../pktgen-dpdk/app/pktgen-gui.c:23:81: note: in definition of macro 'stats_store'
   23 |         gtk_tree_store_set(treestore_stats[(p)], &toplevel, COL_CHASSIS_PORTS, (v), -1); \
      |                                                                                 ^
../pktgen-dpdk/app/pktgen-gui.c:306:9: note: in expansion of macro 'stats_store_next'
  306 |         stats_store_next(pid, info->sizes.jumbo);
      |         ^~~~~~~~~~~~~~~~
../pktgen-dpdk/app/pktgen-gui.c:321:37: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'stats'; did you mean 'qstats'?
  321 |         stats_store_next(pid, info->stats.arp_pkts);
      |                                     ^~~~~
../pktgen-dpdk/app/pktgen-gui.c:23:81: note: in definition of macro 'stats_store'
   23 |         gtk_tree_store_set(treestore_stats[(p)], &toplevel, COL_CHASSIS_PORTS, (v), -1); \
      |                                                                                 ^
../pktgen-dpdk/app/pktgen-gui.c:321:9: note: in expansion of macro 'stats_store_next'
  321 |         stats_store_next(pid, info->stats.arp_pkts);
      |         ^~~~~~~~~~~~~~~~
../pktgen-dpdk/app/pktgen-gui.c:322:37: error: 'port_info_t' {aka 'struct port_info_s'} has no member named 'stats'; did you mean 'qstats'?
  322 |         stats_store_next(pid, info->stats.echo_pkts);
      |                                     ^~~~~
../pktgen-dpdk/app/pktgen-gui.c:23:81: note: in definition of macro 'stats_store'
   23 |         gtk_tree_store_set(treestore_stats[(p)], &toplevel, COL_CHASSIS_PORTS, (v), -1); \
      |                                                                                 ^
../pktgen-dpdk/app/pktgen-gui.c:322:9: note: in expansion of macro 'stats_store_next'
  322 |         stats_store_next(pid, info->stats.echo_pkts);
      |         ^~~~~~~~~~~~~~~~
```

Probably caused by https://github.com/pktgen/Pktgen-DPDK/commit/f2e1aca3a893f485767eea6d2be5fdedf738aed4

**Comment by KeithWiles** [comment]
This should be fixed for Lua builds in the 22.04.1 release.

**Comment by a-andre** [comment]
Thanks for fixing the lua builds. Could we keep the issue open for the GUI part?

**Comment by KeithWiles** [comment]
Fixed in next release.
