### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by Meamarian** [pktgen/Pktgen-DPDK#303]
Hi,
I have tested with dpdk24.03 and 23.03, both stocks here:
last commit from pktgen.

server info:
uname -r
5.15.0-130-generic
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04

Pktgen-DPDK$ sudo make -j
>>> Use 'make help' for more commands

./tools/pktgen-build.sh build
>>  SDK Path          : /home/admin/mohsen
>>  Install Path      : /home/admin/mohsen/Pktgen-DPDK
>>  Build Directory   : /home/admin/mohsen/Pktgen-DPDK/builddir
>>  Target Directory  : usr/local
>>  Build Path        : /home/admin/mohsen/Pktgen-DPDK/builddir
>>  Target Path       : /home/admin/mohsen/Pktgen-DPDK/usr/local

 Build and install values:
   lua_enabled       : -Denable_lua=false

>>> Ninja build in '/home/admin/mohsen/Pktgen-DPDK/builddir' buildtype=release
meson setup -Dbuildtype=release -Denable_lua=false /home/admin/mohsen/Pktgen-DPDK/builddir
The Meson build system
Version: 0.61.2
Source dir: /home/admin/mohsen/Pktgen-DPDK
Build dir: /home/admin/mohsen/Pktgen-DPDK/builddir
Build type: native build
Program cat found: YES (/usr/bin/cat)
Project name: pktgen
Project version: 24.10.3
C compiler for the host machine: ccache cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C linker for the host machine: cc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -mavx: YES 
Compiler for C supports arguments -mavx2: YES 
Compiler for C supports arguments -Wno-pedantic: YES 
Compiler for C supports arguments -Wno-format-truncation: YES 
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Found CMake: /usr/bin/cmake (3.22.1)
Run-time dependency libfgen found: NO (tried pkgconfig and cmake)
Run-time dependency libdpdk found: YES 23.03.0
Message: prefix: /usr/local libdir: lib/x86_64-linux-gnu
Message: DPDK lib path: /usr/local/lib/x86_64-linux-gnu
Library rte_net_bond found: YES
Program python3 found: YES (/usr/bin/python3)
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.platlibdir" option.
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.purelibdir" option.
Library rte_net_i40e found: YES
Library rte_net_ixgbe found: YES
Library rte_net_ice found: YES
Library rte_bus_vdev found: YES
Run-time dependency threads found: YES
Run-time dependency numa found: YES 2.0.14
Run-time dependency pcap found: YES 1.10.5
Library dl found: YES
Library m found: YES
Library bsd found: YES
Program doxygen found: NO
Program sphinx-build found: NO
Build targets in project: 9

pktgen 24.10.3

  User defined options
    buildtype : release
    enable_lua: false

Found ninja-1.10.1 at /usr/bin/ninja
ninja: Entering directory `/home/admin/mohsen/Pktgen-DPDK/builddir'
[9/64] Compiling C object lib/utils/libutils.a.p/_atoip.c.o
FAILED: lib/utils/libutils.a.p/_atoip.c.o 
ccache cc -Ilib/utils/libutils.a.p -Ilib/utils -I../lib/utils -Ilib/common -I../lib/common -I/usr/local/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/libnl3 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -O3 -march=native -mavx -mavx2 -DALLOW_EXPERIMENTAL_API -D_GNU_SOURCE -Wno-pedantic -Wno-format-truncation -fPIC -include rte_config.h -march=native -MD -MQ lib/utils/libutils.a.p/_atoip.c.o -MF lib/utils/libutils.a.p/_atoip.c.o.d -o lib/utils/libutils.a.p/_atoip.c.o -c ../lib/utils/_atoip.c
In file included from ../lib/utils/_atoip.c:6:
../lib/utils/_atoip.h:35:30: error: field ‘ipv6’ has incomplete type
   35 |         struct rte_ipv6_addr ipv6;
      |                              ^~~~
[12/64] Compiling C object lib/common/libcommon.a.p/cksum.c.o
FAILED: lib/common/libcommon.a.p/cksum.c.o 
ccache cc -Ilib/common/libcommon.a.p -Ilib/common -I../lib/common -Ilib/hmap -I../lib/hmap -I/usr/local/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/libnl3 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -O3 -march=native -mavx -mavx2 -DALLOW_EXPERIMENTAL_API -D_GNU_SOURCE -Wno-pedantic -Wno-format-truncation -fPIC -include rte_config.h -march=native -MD -MQ lib/common/libcommon.a.p/cksum.c.o -MF lib/common/libcommon.a.p/cksum.c.o.d -o lib/common/libcommon.a.p/cksum.c.o -c ../lib/common/cksum.c
In file included from ../lib/common/cksum.c:73:
../lib/common/pg_inet.h:46:30: error: field ‘ipv6’ has incomplete type
   46 |         struct rte_ipv6_addr ipv6;
      |                              ^~~~
[22/64] Compiling C object lib/cli/libcli.a.p/cli_auto_complete.c.o
ninja: build stopped: subcommand failed.
make: *** [Makefile:15: build] Error 1

**Comment by cueltschey** [comment]
I tried to fix this and could not get it working. Try installing linux-headers-(kernel-version)-generic. I think it may have to do with the version of libdpd-dev on ubuntu 22.04.

**Comment by KeithWiles** [comment]
Thanks I hope to have  a look at this on the weekend. I know Pktgen builds on my Ubuntu 24.10 version and normally I do not have a setup to build on older versions of Ubuntu. What version of DPDK are you using?

**Comment by mindbound** [comment]
I am also having the same issue on Ubuntu 22.04, I have DPDK 22.11.7 installed.

**Comment by KeithWiles** [comment]
I can't support older versions of DPDK and/or Pktgen, sorry. I just do not have the setup or bandwidth to fix older versions. I am happy to take pull requests to fix Pktgen if you want to go that direction.

I would suggest installing the latest DPDK and Pktgen then build Pktgen into a binary. You can still use the old DPDK in your application, if required. If you need some old PMD or feature in an older DPDK version, then you will have a problem with pktgen using a newer version of DPDK.

If you can't get the newer version of DPDK or Pktgen to build in an older kernel or distro then I will not be able to help much.

**Comment by HenriqueBBrum** [comment]
> I tried to fix this and could not get it working. Try installing linux-headers-(kernel-version)-generic. I think it may have to do with the version of libdpd-dev on ubuntu 22.04.

Hello, I was having the same issue, "error: field ‘ipv6’ has incomplete type", with DPDK 25.07.0, Pktgen 25.07.0 and Ubuntu 24.04. 

The problem comes from **libbsd-dev**. I uninstalled it and installed again, and the problem was solved.
