### ISSUE TITLE
multi-queue concurrent test packet loss

### ISSUE THREAD

**Issue by ChenYahui2019** [pktgen/Pktgen-DPDK#367]
pktgen version: 24.03
DPDK version: 23.11
kernel: ubuntu 5.15.0-163-generic

network topo:
<img width="802" height="603" alt="Image" src="https://github.com/user-attachments/assets/a2e534b7-0d1e-4322-8f8b-368a5dae352c" />

<img width="1753" height="438" alt="Image" src="https://github.com/user-attachments/assets/7e5d143f-2da8-4667-a1aa-052a75592806" />

I run pktgen with the command below which give only one queues per port:
`pktgen -a 0000:85:00.5 -a 0000:85:00.6 -l 37-53 -- -p 0x3 -m [38].0,[48].1 -f sequence.pkg`
The pps can be more than 15Mpps with zero packet loss.

I run pktgen with the command below which give 8 queues per port:
`pktgen -a 0000:85:00.5 -a 0000:85:00.6 -l 37-53 -- -p 0x3 -m [38-45].0,[46-53].1 -f sequence.pkg`

<img width="1326" height="673" alt="Image" src="https://github.com/user-attachments/assets/78774949-44a3-45a3-acfd-9abe68918c72" />
Total pps of all queues is even less than pps of one queue, and there are also packet losses.

The kernel isolcpu config: 
`isolcpus=managed_irq,domain,37-70 rcu_nocbs=37-70`

The cpu and nic are on the same NUMA node.

It seems there are concurrent bugs of pktgen.

**Comment by KeithWiles** [comment]
Please update to the Pktgen to 25.08.1 and the latest DPDK version 25.11.0 as I fixed a few problems with Pktgen this year.

I can not debug older versions as I do not have the time or setup.

BTW you can remove the -p 0x3 as it has not been used for a long time now.

Thanks

**Comment by ChenYahui2019** [comment]
I recompile with DPDK: https://fast.dpdk.org/rel/dpdk-25.11.tar.xz

pktgen latest tag is 25.08.0 which build fail: error: 'RTE_ETHDEV_QUEUE_STAT_CNTRS' undeclared here (not in a function)

The lastest main branch can build, but failed to run:
====== Pktgen got a Segment Fault

Obtained 9 stack frames.
pktgen(+0x2816c) [0x56001200016c]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f60067a1520]
pktgen(+0x33887) [0x56001200b887]
pktgen(+0x32bd0) [0x56001200abd0]
pktgen(+0x37363) [0x56001200f363]
/usr/local/lib/x86_64-linux-gnu/librte_eal.so.26(+0x290e6) [0x7f6006b2b0e6]
/usr/local/lib/x86_64-linux-gnu/librte_eal.so.26(+0x3ab5f) [0x7f6006b3cb5f]
/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f60067f3ac3]
/lib/x86_64-linux-gnu/libc.so.6(+0x1268c0) [0x7f60068858c0]

**Comment by ChenYahui2019** [comment]
reopen the issue

**Comment by KeithWiles** [comment]
Sorry, it appears you need to use Pktgen version 25.08.1 and DPDK version 26.03.0-rc0 as DPDK changed the way stats are collected. The 'RTE_ETHDEV_QUEUE_STAT_CNTRS' not available anymore. I must have not pushed the changes to the repo :-)

**Comment by ChenYahui2019** [comment]
> Sorry, it appears you need to use Pktgen version 25.08.1 and DPDK version 26.03.0-rc0 as DPDK changed the way stats are collected. The 'RTE_ETHDEV_QUEUE_STAT_CNTRS' not available anymore. I must have not pushed the changes to the repo :-)

FAILED: lib/common/libcommon.a.p/cksum.c.o
cc -Ilib/common/libcommon.a.p -Ilib/common -I../lib/common -Ilib/hmap -I../lib/hmap -I/opt/mellanox/dpdk/include/dpdk -I/opt/mellanox/dpdk/include/dpdk/../x86_64-linux-gnu/dpdk -I/usr/include/libnl3 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -O3 -march=native -mavx -mavx2 -DALLOW_EXPERIMENTAL_API -D_GNU_SOURCE -Wno-pedantic -Wno-format-truncation -fPIC -include rte_config.h -march=corei7 -MD -MQ lib/common/libcommon.a.p/cksum.c.o -MF lib/common/libcommon.a.p/cksum.c.o.d -o lib/common/libcommon.a.p/cksum.c.o -c ../lib/common/cksum.c
In file included from ../lib/common/cksum.c:73:
../lib/common/pg_inet.h:46:30: error: field ‘ipv6’ has incomplete type
   46 |         struct rte_ipv6_addr ipv6;
      |                              ^~~~
ninja: build stopped: subcommand failed.

**Comment by pktgen** [comment]
I am using Ubuntu 25.10 version with kernel 6.17, this is most likely the source of this error.

What is the Ubuntu version you are using?

I will try to figure out the problem, but I do not have a Ubuntu version at hand.

**Comment by ChenYahui2019** [comment]
> I am using Ubuntu 25.10 version with kernel 6.17, this is most likely the source of this error.
> 
> What is the Ubuntu version you are using?
> 
> I will try to figure out the problem, but I do not have a Ubuntu version at hand.

Ubuntu 22.04.4 LTS, kernel version: 5.15.0-163-generic

**Comment by pktgen** [comment]
I can't find the problem with my Ubuntu 25.10.

If you could please update to 25.10 or create a container/VM with the 25.10 version. The binary created should work in your 22.04.4 LTS system. If that does not help it will be some time before I have the time to look into the problem more closely.
